const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  getWordInfo: (term, reading) => ipcRenderer.invoke('get-word-info', term, reading),
  recordLookup: (term, reading, contextSentence) => ipcRenderer.invoke('record-lookup', term, reading, contextSentence),
  updateWordStatus: (term, reading, status, contextSentence) => ipcRenderer.invoke('update-word-status', term, reading, status, contextSentence),
  getWordStatuses: (terms) => ipcRenderer.invoke('get-word-statuses', terms),
  importDictionary: () => ipcRenderer.invoke('import-dictionary'),
  getDictionaries: () => ipcRenderer.invoke('get-dictionaries'),
  removeDictionary: (id) => ipcRenderer.invoke('remove-dictionary', id),
  getLibrary: () => ipcRenderer.invoke('get-library'),
  addManga: () => ipcRenderer.invoke('add-manga'),
  removeManga: (id) => ipcRenderer.invoke('remove-manga', id),
  loadManga: (id) => ipcRenderer.invoke('load-manga', id),
  saveMangaData: (id, mangaData) => ipcRenderer.invoke('save-manga-data', id, mangaData),
  getMangaImage: (imageName) => ipcRenderer.invoke('get-manga-image', imageName),
  updateLastRead: (id, pageIndex) => ipcRenderer.invoke('update-last-read', id, pageIndex),
  getWordsByStatus: (status) => ipcRenderer.invoke('get-words-by-status', status),
  getRandomDictionaryWord: () => ipcRenderer.invoke('get-random-dictionary-word'),
  getQuizStats: (term, reading) => ipcRenderer.invoke('get-quiz-stats', term, reading),
  updateQuizStats: (term, reading, isCorrect) => ipcRenderer.invoke('update-quiz-stats', term, reading, isCorrect),
  getMasteryProgress: (days) => ipcRenderer.invoke('get-mastery-progress', days),
  searchDictionary: (query) => ipcRenderer.invoke('search-dictionary', query),
  evaluateTranslation: (term, reading, translation, mode, contextSentence) => ipcRenderer.invoke('evaluate-translation', term, reading, translation, mode, contextSentence),
  analyzeImageRegion: (imageBuffer, x, y, width, height) => ipcRenderer.invoke('analyze-image-region', imageBuffer, x, y, width, height),
  chatWithLLM: (messages, context) => ipcRenderer.invoke('chat-with-llm', messages, context),
  getSettings: () => ipcRenderer.invoke('get-settings'),
  updateSetting: (key, value) => ipcRenderer.invoke('update-setting', key, value),
  getMangaChats: (mangaId) => ipcRenderer.invoke('get-manga-chats', mangaId),
  createMangaChat: (mangaId, title) => ipcRenderer.invoke('create-manga-chat', mangaId, title),
  updateMangaChat: (chatId, title) => ipcRenderer.invoke('update-manga-chat', chatId, title),
  deleteMangaChat: (chatId) => ipcRenderer.invoke('delete-manga-chat', chatId),
  getChatMessages: (chatId) => ipcRenderer.invoke('get-chat-messages', chatId),
  addChatMessage: (chatId, role, content) => ipcRenderer.invoke('add-chat-message', chatId, role, content),
  getStickyNotes: (mangaId) => ipcRenderer.invoke('get-sticky-notes', mangaId),
  saveStickyNote: (note) => ipcRenderer.invoke('save-sticky-note', note),
  deleteStickyNote: (id) => ipcRenderer.invoke('delete-sticky-note', id),
  saveStroke: (strokeData) => ipcRenderer.invoke('save-stroke', strokeData),
  getStrokes: (noteId) => ipcRenderer.invoke('get-strokes', noteId),
  deleteStroke: (id) => ipcRenderer.invoke('delete-stroke', id),
  selectMangaCover: () => ipcRenderer.invoke('select-manga-cover'),
  saveCroppedCover: (id, base64) => ipcRenderer.invoke('save-cropped-cover', id, base64),
  getMangaCoverUrl: (coverPath) => ipcRenderer.invoke('get-manga-cover-url', coverPath),
  getAllUserWords: () => ipcRenderer.invoke('get-all-user-words'),
  deleteUserWord: (term, reading) => ipcRenderer.invoke('delete-user-word', term, reading),
  banUserWord: (term, reading) => ipcRenderer.invoke('ban-user-word', term, reading),
  markNonJapanese: (term, reading) => ipcRenderer.invoke('mark-non-japanese', term, reading),
  clearAllData: (type) => ipcRenderer.invoke('clear-all-data', type),
  exportData: (type) => ipcRenderer.invoke('export-data', type),
  onMangaProgress: (callback) => {
    ipcRenderer.on('manga-progress', (_event, data) => callback(data));
  },
  removeMangaProgress: () => {
    ipcRenderer.removeAllListeners('manga-progress');
  }
});
